{% set name = "objectgraph" %}
{% set version = "1.0.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/objectgraph-{{ version }}.tar.gz
  sha256: 4f214c1d72c1dd1c2122b1d7b3348169834e99bb88aab0a4e1de2bfd01316451

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - flit
    - python {{ python_min }}
  run:
    - python >={{ python_min }},<4.0
    - typing_extensions

test:
  imports:
    - objectgraph
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://objectgraph.readthedocs.io/
  summary: A basic graph library
  license: MIT
  license_file: doc/license.rst

extra:
  recipe-maintainers:
    - nehaljwani
